import type { PatientRecord } from "types/patient";

export const SEED: PatientRecord[] = [
  {
    id: "pat-001",
    fullName: "Şule Özdemir",
    birthDate: "1980-04-01",
    appointmentDate: "2024-02-14T00:00:00",
    createdAt: "2023-09-12T00:00:00",
    department: "Nöroloji",
    status: "İptal",
    priority: "acil",
    bloodType: "B-",
    score: 2,
    note_tr: "Ek tetkik istendi.",
    note_en: "Complaints have decreased.",
    diagnosis_tr: "Hipotiroidi",
    diagnosis_en: "Hypothyroidism",
    isInsured: true,
    isFollowUp: false,
    isVaccinated: true,
    tags: ["kalp", "kronik", "romatizma"],
    notes: null,
  },
  {
    id: "pat-002",
    fullName: "Şule Yılmaz",
    birthDate: "1964-09-22",
    appointmentDate: "2024-07-23T00:00:00",
    createdAt: "2023-01-04T00:00:00",
    department: "Dahiliye",
    status: "Bekliyor",
    priority: "acil",
    bloodType: "AB+",
    score: 2,
    note_tr: "Hasta düzenli kontrole gelmektedir.",
    note_en: "Complaints have decreased.",
    diagnosis_tr: "Migren",
    diagnosis_en: "Migraine",
    isInsured: true,
    isFollowUp: false,
    isVaccinated: true,
    tags: ["hipertansiyon", "obezite"],
    notes: null,
  },
  {
    id: "pat-005",
    fullName: "Kaan Şimşek",
    birthDate: "1983-04-02",
    appointmentDate: "2025-08-19T00:00:00",
    createdAt: "2024-12-15T00:00:00",
    department: "Dahiliye",
    status: "Tamamlandı",
    priority: "normal",
    bloodType: "0+",
    score: 4,
    note_tr: "Diyet programı başlatıldı.",
    note_en: "Additional tests requested.",
    diagnosis_tr: "Lomber Disk Hernisi",
    diagnosis_en: "Lumbar Disc Herniation",
    isInsured: true,
    isFollowUp: false,
    isVaccinated: true,
    tags: ["romatizma", "diyabet", "migren"],
    notes: "Hasta takip altında.",
  },
  {
    id: "pat-008",
    fullName: "Yusuf Kılıç",
    birthDate: "1970-03-18",
    appointmentDate: "2025-12-12T00:00:00",
    createdAt: "2023-10-20T00:00:00",
    department: "Pediatri",
    status: "Muayenede",
    priority: "acil",
    bloodType: "B-",
    score: 3,
    note_tr: "Uyku düzensizliği rapor edildi.",
    note_en: "Patient attends regular check-ups.",
    diagnosis_tr: "Migren",
    diagnosis_en: "Migraine",
    isInsured: true,
    isFollowUp: true,
    isVaccinated: true,
    tags: ["hipertansiyon"],
    notes: "Ek bilgi bekleniyor.",
  },
  {
    id: "pat-014",
    fullName: "Can Yıldız",
    birthDate: "1966-09-14",
    appointmentDate: "2024-03-09T00:00:00",
    createdAt: "2024-01-30T00:00:00",
    department: "Nöroloji",
    status: "Tamamlandı",
    priority: "normal",
    bloodType: "B+",
    score: 5,
    note_tr: "Fizik tedavi önerildi.",
    note_en: "Additional tests requested.",
    diagnosis_tr: "Tip 2 Diyabet",
    diagnosis_en: "Type 2 Diabetes",
    isInsured: true,
    isFollowUp: true,
    isVaccinated: true,
    tags: ["kronik"],
    notes: null,
  },
  {
    id: "pat-018",
    fullName: "Hüseyin Aydın",
    birthDate: "1956-01-09",
    appointmentDate: "2025-12-11T00:00:00",
    createdAt: "2023-10-26T00:00:00",
    department: "Kardiyoloji",
    status: "Muayenede",
    priority: "acil",
    bloodType: "AB-",
    score: 1,
    note_tr: "İlaç kullanımı devam ediyor.",
    note_en: "Stress-related symptoms present.",
    diagnosis_tr: "Hipertansiyon",
    diagnosis_en: "Hypertension",
    isInsured: true,
    isFollowUp: true,
    isVaccinated: false,
    tags: ["migren", "hipertansiyon"],
    notes: "Ek bilgi bekleniyor.",
  },
  {
    id: "pat-021",
    fullName: "Tuğba Kaya",
    birthDate: "1987-07-26",
    appointmentDate: "2025-03-09T00:00:00",
    createdAt: "2024-07-07T00:00:00",
    department: "Ortopedi",
    status: "Tamamlandı",
    priority: "acil",
    bloodType: "B+",
    score: 2,
    note_tr: "Ameliyat sonrası takip sürecinde.",
    note_en: "Stress-related symptoms present.",
    diagnosis_tr: "Gastrit",
    diagnosis_en: "Gastritis",
    isInsured: true,
    isFollowUp: true,
    isVaccinated: true,
    tags: ["kronik", "obezite", "alerji"],
    notes: "Hasta takip altında.",
  },
];
